name: Build and Publish to NPM

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint code
        run: pnpm lint

      - name: Build library
        run: pnpm ng build ngx-json-visualizer --configuration production

      - name: Update package version
        working-directory: ./dist/ngx-json-visualizer
        run: |
          # Extract version from git tag (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Publishing version: $VERSION"
          npm version $VERSION --no-git-tag-version

      - name: Publish to NPM
        working-directory: ./dist/ngx-json-visualizer
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## 🚀 New Release: ${{ github.ref_name }}

            ### Changes in this Release
            - Library built and published to NPM as version ${{ github.ref_name }}
            - Available at: https://www.npmjs.com/package/ngx-json-visualizer

            ### Installation
            ```bash
            npm install ngx-json-visualizer@${{ github.ref_name }}
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
